import pg from 'pg';
import crypto from 'crypto';
import {signCrmPayload} from '../src/server/crm/signature';

// Destructive test fixtures are allowed ONLY on the disposable local database used by this script.
// Start the disposable test server with DEFAULT_STUDENT_PASSWORD=LocalTestOnly_2026! for CRM login checks.
const base=process.env.E2E_BASE_URL || 'http://localhost:3101';
const dbUrl=process.env.DATABASE_URL || '';
const parsed=new URL(dbUrl);
if(!['127.0.0.1','localhost'].includes(new URL(base).hostname) || new URL(base).port!=='3101' || parsed.hostname!=='127.0.0.1' || parsed.port!=='55433' || parsed.pathname!=='/lms_mcna_codex_test') throw new Error('Refusing to run outside disposable local test database.');
const db=new pg.Pool({connectionString:dbUrl}),run=crypto.randomBytes(4).toString('hex');let checks=0;
type Session={cookie:string;csrf:string;user:any};
const assert=(condition:any,message:string)=>{if(!condition)throw new Error(message);checks++;};
async function login(email:string,password:string):Promise<Session>{
  const res=await fetch(`${base}/api/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});
  const data=await res.json();assert(res.ok,`Login: ${JSON.stringify(data)}`);
  return {cookie:res.headers.getSetCookie().map(c=>c.split(';')[0]).join('; '),csrf:data.csrfToken,user:data.user};
}
async function call(path:string,session:Session|null=null,payload?:any,status:number|number[]=200,method=payload===undefined?'GET':'POST',headers:Record<string,string>={}) {
  const isForm=payload instanceof FormData;
  const response=await fetch(`${base}${path}`,{method,headers:{...(session?{Cookie:session.cookie,'X-CSRF-Token':session.csrf}:{}),...(!isForm?{'Content-Type':'application/json'}:{}),...headers},body:payload===undefined?undefined:isForm?payload:JSON.stringify(payload),redirect:'manual'});
  const raw=await response.text();let data:any;try{data=JSON.parse(raw);}catch{data=raw;}
  assert((Array.isArray(status)?status:[status]).includes(response.status),`${method} ${path}: expected ${status}, got ${response.status} ${raw.slice(0,400)}`);
  console.log(`  ✓ ${method} ${path}: ${status}`);return data;
}
const ops=(path:string,s:Session,payload?:any,status:number|number[]=200,method?:string)=>call(`/api/operations${path}`,s,payload,status,method);
// Valid one-page PDF also used for visual checks of the private viewer.
const pageStream='BT /F1 18 Tf 40 740 Td (MCNA local operations test) Tj ET';
const pdfObjects=['<</Type /Catalog /Pages 2 0 R>>','<</Type /Pages /Kids [3 0 R] /Count 1>>',
  '<</Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources <</Font <</F1 5 0 R>>>> /Contents 4 0 R>>',
  `<</Length ${pageStream.length}>>\nstream\n${pageStream}\nendstream`,'<</Type /Font /Subtype /Type1 /BaseFont /Helvetica>>'];
let pdf='%PDF-1.4\n';const pdfOffsets=[0];
pdfObjects.forEach((object,i)=>{pdfOffsets.push(Buffer.byteLength(pdf));pdf+=`${i+1} 0 obj\n${object}\nendobj\n`;});
const xref=Buffer.byteLength(pdf);
pdf+=`xref\n0 6\n0000000000 65535 f \n${pdfOffsets.slice(1).map(offset=>`${String(offset).padStart(10,'0')} 00000 n \n`).join('')}trailer\n<</Size 6 /Root 1 0 R>>\nstartxref\n${xref}\n%%EOF`;
async function upload(s:Session,name:string,contents:string,mime:string){const form=new FormData();form.append('file',new Blob([contents],{type:mime}),name);return call('/api/upload',s,form);}
async function crm(path:string,payload:any){const raw=JSON.stringify(payload),timestamp=String(Math.floor(Date.now()/1000));return call(`/api/integrations/crm${path}`,null,payload,path==='/payments/confirm'?200:201,'POST',{'Authorization':'Bearer local-crm-test-token','X-CRM-Timestamp':timestamp,'X-CRM-Signature':`sha256=${signCrmPayload('local-crm-signature-test-secret',timestamp,raw)}`,'X-CRM-Event-Id':`ops-${run}-${crypto.randomUUID()}`});}

async function main(){
  const admin=await login('admin@mcna.local','admine16');
  const mgrRow=await call('/api/admin/users',admin,{name:'Operations Manager',email:`ops.manager.${run}@example.com`,password:'Manager@12345',role:'manager'},201);
  const manager=await login(mgrRow.email,'Manager@12345');
  console.log('1. Settings, teacher subjects and account isolation');
  const teacherRow=await ops('/teachers',manager,{name:'Operations Teacher',email:`ops.teacher.${run}@example.com`,password:'Teacher@12345',courseIds:[]});
  const teacher=await login(teacherRow.email,'Teacher@12345');
  await ops('/teachers',teacher,undefined,403); // First-login password gate.
  await call('/api/users/change-password',teacher,{currentPassword:'Teacher@12345',newPassword:'Teacher@67890'});
  const otherRow=await ops('/teachers',manager,{name:'Other Teacher',email:`ops.otherteacher.${run}@example.com`,password:'Teacher@12345',courseIds:[]});
  const otherTeacher=await login(otherRow.email,'Teacher@12345');await call('/api/users/change-password',otherTeacher,{currentPassword:'Teacher@12345',newPassword:'Teacher@67890'});
  await ops('/teachers',manager,{name:'Privilege escalation',email:`evil.${run}@example.com`,password:'Teacher@12345',courseIds:[],role:'admin'},400);
  const course=await call('/api/courses',manager,{title:`Operations ${run}`,description:'Local E2E test course',teacherId:otherRow.id,category:'Test',price:1000000,numberOfLessons:2},201);
  const next=await call('/api/courses',manager,{title:`Next ${run}`,description:'Next course',teacherId:teacherRow.id,category:'Test',price:2000000,numberOfLessons:2},201);
  await ops(`/teachers/${teacherRow.id}/subjects`,manager,{courseIds:[course.id]},200,'PUT');
  const rules={absentStatuses:['absent'],tierRules:[{label:'1.1',courses:0},{label:'1.2',courses:2}],commissionStart:'2026-01-01',bankBin:'',bankAccount:'',bankName:''};
  await ops('/settings',manager,rules,403,'PUT');await ops('/settings',admin,rules,200,'PUT');
  await ops('/settings',admin,{...rules,commissionStart:'2026-02-30'},400,'PUT');
  await ops(`/teachers/${admin.user.id}/subjects`,manager,{courseIds:[]},404,'PUT');
  const makeSection=async(code:string,t=teacherRow.id)=>call('/api/course-sections',manager,{courseId:course.id,teacherId:t,sectionCode:`OPS-${code}-${run}`,maxStudents:10,numberOfSessions:2,openingDate:'2026-09-01',schedule:[{dayOfWeek:'Thứ Ba',startTime:code==='COPY'?'07:00':'05:00',endTime:code==='COPY'?'09:00':'07:00',room:'Online'}],status:'open',groupChatUrl:'https://zalo.me/g/test'},201);
  const a=await makeSection('A'),b=await makeSection('B',otherRow.id),copy=await makeSection('COPY');
  await call('/api/course-sections',manager,{courseId:course.id,teacherId:mgrRow.id,sectionCode:`BAD-${run}`,maxStudents:10,numberOfSessions:2,status:'open',schedule:[]},400);
  const teacherNoticeCount=async()=>Number((await db.query("SELECT COUNT(*)::int n FROM notifications WHERE user_id=$1 AND related_entity_id=$2 AND message LIKE 'Bạn được phân công%'",[teacherRow.id,a.id])).rows[0].n);
  assert(await teacherNoticeCount()===1,'Exactly one teacher assignment notice expected.');
  await call(`/api/course-sections/${a.id}`,manager,{courseId:course.id,teacherId:teacherRow.id,sectionCode:a.sectionCode,maxStudents:10,numberOfSessions:2,openingDate:'2026-09-01',schedule:[{dayOfWeek:'Thứ Ba',startTime:'05:00',endTime:'07:00',room:'Online'}],status:'open',groupChatUrl:'https://zalo.me/g/test'},200,'PUT');
  assert(await teacherNoticeCount()===1,'Identical class update must not resend teacher notice.');
  console.log('2. Paid learners, class scope and private briefs');
  const emails=['one','two','waiting'].map(n=>`ops.${n}.${run}@example.com`);
  await call('/api/admin/paid-enrollments/import',manager,{rows:emails.map((email,i)=>({name:`Learner ${i+1}`,email,course:course.title,amount:1000000})),defaultPassword:'LocalTestOnly_2026!',sendAccountEmail:false});
  const learners=await Promise.all(emails.map(email=>login(email,'LocalTestOnly_2026!')));for(const learner of learners)await call('/api/users/change-password',learner,{currentPassword:'LocalTestOnly_2026!',newPassword:'Student@67890'});
  const enrollmentIds=await Promise.all(learners.map(async l=>(await db.query('SELECT id FROM enrollments WHERE student_id=$1 AND course_id=$2',[l.user.id,course.id])).rows[0].id));
  await call('/api/admin/enrollments/bulk-place',manager,{placements:[{enrollmentId:enrollmentIds[0],sectionId:a.id},{enrollmentId:enrollmentIds[1],sectionId:b.id}]});
  const sessionsA=(await db.query('SELECT * FROM attendance_sessions WHERE section_id=$1 ORDER BY date',[a.id])).rows;
  const sessionsB=(await db.query('SELECT * FROM attendance_sessions WHERE section_id=$1 ORDER BY date',[b.id])).rows;
  const brief=await upload(teacher,'brief.pdf',pdf,'application/pdf');
  const assignment=await call('/api/assignments',teacher,{courseId:course.id,sessionId:sessionsA[0].id,title:'Final work',description:'Complete final project',deadline:'2030-01-01T00:00:00Z',maxScore:10,type:'final',attachmentUrl:brief.url,allowLate:true},201);
  await call(brief.url,null,undefined,401);await call(brief.url,learners[0],undefined,403);
  await call(brief.url,learners[0],undefined,200,'GET',{'X-LMS-Viewer':'1'});await call(brief.url,learners[1],undefined,403,'GET',{'X-LMS-Viewer':'1'});
  await call(brief.url.replace('/uploads/','/%75ploads/'),null,undefined,404);
  await ops(`/sessions/${sessionsA[0].id}`,otherTeacher,undefined,403);
  await call('/api/assignments/submit',learners[1],{assignmentId:assignment.id,content:'Wrong class'},403);
  await call('/api/assignments/submit',learners[2],{assignmentId:assignment.id,content:'Unplaced'},403);
  const file=await upload(learners[0],'submission.csv','value\n1','text/csv');
  await call('/api/assignments/submit',learners[1],{assignmentId:assignment.id,content:'Steal upload',attachmentUrl:file.url},403);
  const first=await call('/api/assignments/submit',learners[0],{assignmentId:assignment.id,content:'Version one',attachmentUrl:file.url},201);
  await call('/api/assignments/grade',otherTeacher,{submissionId:first.id,score:5,feedback:'No',expectedSubmittedAt:first.submittedAt},403);
  await call('/api/assignments/grade',teacher,{submissionId:first.id,score:11,feedback:'No',expectedSubmittedAt:first.submittedAt},400);
  await call('/api/assignments/grade',teacher,{submissionId:first.id,score:8,feedback:'Good',expectedSubmittedAt:first.submittedAt});
  const revised=await call('/api/assignments/submit',learners[0],{assignmentId:assignment.id,content:'Version two'},201);
  assert(revised.score===undefined,'Resubmission must clear old grade.');
  await call('/api/assignments/grade',teacher,{submissionId:first.id,score:8,feedback:'Stale',expectedSubmittedAt:first.submittedAt},409);
  const history=await ops(`/submissions/${first.id}/history`,learners[0]);assert(history.length===1 && history[0].content==='Version one','Revision history missing.');
  const parallelRevisions=await Promise.all(['Concurrent A','Concurrent B'].map(content=>call('/api/assignments/submit',learners[0],{assignmentId:assignment.id,content},201)));
  assert(parallelRevisions[0].id===parallelRevisions[1].id && parallelRevisions[0].submittedAt!==parallelRevisions[1].submittedAt,'Concurrent resubmission lost revision identity.');
  assert((await ops(`/submissions/${first.id}/history`,learners[0])).length===3,'Concurrent revisions overwrote history.');
  const expired=await call('/api/assignments',teacher,{courseId:course.id,sessionId:sessionsA[0].id,title:'Closed homework',description:'Deadline test',deadline:'2020-01-01T00:00:00Z',maxScore:10,type:'lesson',allowLate:false},201);
  await call('/api/assignments/submit',learners[0],{assignmentId:expired.id,content:'Late'},400);
  await ops(`/submissions/${first.id}/history`,learners[1],undefined,403);await call(file.url,learners[1],undefined,403);
  const solution=await upload(teacher,'solution.pdf',pdf,'application/pdf');
  await ops(`/sessions/${sessionsA[0].id}/solution`,teacher,{content:'Private answer',attachmentUrl:solution.url,published:false},200,'PUT');
  assert(await ops(`/sessions/${sessionsA[0].id}/solution`,learners[0])===null,'Unpublished answer must not be returned.');
  await call(solution.url,learners[0],undefined,403,'GET',{'X-LMS-Viewer':'1'});
  await ops(`/sessions/${sessionsA[0].id}/solution`,teacher,{content:'Published answer',attachmentUrl:solution.url,published:true},200,'PUT');
  assert((await ops(`/sessions/${sessionsA[0].id}/solution`,learners[0])).content==='Published answer','Published solution missing.');
  console.log('3. Immutable template snapshots and class-specific overrides');
  const materialForm=new FormData();materialForm.append('type','slide');materialForm.append('file',new Blob([pdf],{type:'application/pdf'}),'template.pdf');
  const material=await call(`/api/sessions/${sessionsA[0].id}/materials`,teacher,materialForm,201);
  const template=await ops('/templates',manager,{sectionId:a.id,title:'MCNA Test Plan'});
  await ops(`/sections/${copy.id}/plan`,teacher,{mode:'default',templateId:template.id});
  await ops(`/sections/${copy.id}/plan`,teacher,{mode:'default',templateId:template.id},400);
  const copiedSessions=(await db.query('SELECT * FROM attendance_sessions WHERE section_id=$1 ORDER BY date',[copy.id])).rows;
  const copiedSolution=await ops(`/sessions/${copiedSessions[0].id}/solution`,teacher);assert(copiedSolution.published===false,'Copied answers must start hidden.');
  const copiedMaterial=(await db.query('SELECT id FROM session_materials WHERE session_id=$1',[copiedSessions[0].id])).rows[0];
  await call(`/api/materials/${material.id}`,teacher,undefined,204,'DELETE');
  await call(`/api/materials/${copiedMaterial.id}/download`,teacher);
  await ops(`/sessions/${copiedSessions[0].id}/solution`,teacher,{content:'Class copy only',published:false},200,'PUT');
  assert((await ops(`/sessions/${sessionsA[0].id}/solution`,teacher)).content==='Published answer','Class override modified source.');
  console.log('4. Attendance, auto-certificates, overrides and actual teaching month');
  await call('/api/certificates/issue',manager,{enrollmentId:enrollmentIds[0]},400);
  await ops(`/sessions/${sessionsA[0].id}/attendance`,teacher,{records:[{studentId:learners[1].user.id,status:'present'}],complete:false},400,'PUT');
  for(const s of sessionsA) await ops(`/sessions/${s.id}/attendance`,teacher,{records:[{studentId:learners[0].user.id,status:'present'}],minutes:120,complete:true},200,'PUT');
  const certs=await ops('/my-certificates',learners[0]);assert(certs.length===1,'Eligible learner must receive exactly one certificate automatically.');
  await ops(`/sections/${a.id}/certificates/reconcile`,manager,{});assert((await ops('/my-certificates',learners[0])).length===1,'Reconciliation duplicated certificate.');
  await call(`/api/public/certificates/${certs[0].certificate_code}`);
  await call('/api/certificates/issue',manager,{enrollmentId:enrollmentIds[1],overrideReason:'Approved exception for local E2E'},201);
  assert((await db.query('SELECT override_reason FROM certificates WHERE enrollment_id=$1',[enrollmentIds[1]])).rows[0].override_reason,'Override reason was not stored.');
  await ops('/teaching/confirm',teacher,{month:'2026-09',note:'Reviewed sessions'});
  await ops('/teaching/review',manager,{teacherId:teacherRow.id,month:'2026-09',status:'approved',note:'Confirmed'});
  const summary=await ops('/teaching?month=2026-09',teacher);assert(summary.monthlyMinutes===240 && summary.courses===1,'Actual teaching totals incorrect.');
  const editClass={courseId:course.id,teacherId:teacherRow.id,sectionCode:a.sectionCode,maxStudents:10,numberOfSessions:2,openingDate:'2026-09-01',schedule:[{dayOfWeek:'Thứ Ba',startTime:'05:00',endTime:'07:00',room:'Online'}],status:'open'};
  await call(`/api/course-sections/${a.id}`,manager,{...editClass,numberOfSessions:1},409,'PUT');
  assert(Number((await db.query('SELECT number_of_sessions FROM course_sections WHERE id=$1',[a.id])).rows[0].number_of_sessions)===2,'Failed shrink partially changed class.');
  await call(`/api/course-sections/${a.id}`,manager,undefined,409,'DELETE');
  await call(`/api/courses/${course.id}`,admin,undefined,409,'DELETE');
  await ops(`/sessions/${sessionsA[0].id}/attendance`,teacher,{records:[{studentId:learners[0].user.id,status:'late'}],minutes:110,complete:true},200,'PUT');
  assert((await ops('/teaching?month=2026-09',teacher)).confirmation.status==='revision','Actual-session edit must invalidate approved month.');
  console.log('4b. Delayed class end is reconciled by authenticated background job');
  await call('/api/admin/enrollments/bulk-place',manager,{placements:[{enrollmentId:enrollmentIds[2],sectionId:copy.id}]});
  const copyFinal=(await db.query("SELECT id FROM assignments WHERE session_id=$1 AND type='final'",[copiedSessions[0].id])).rows[0];
  await call('/api/assignments/submit',learners[2],{assignmentId:copyFinal.id,content:'Final in copied class'},201);
  await db.query("UPDATE attendance_sessions SET date=$1 WHERE id=$2",[new Date(Date.now()-30*60_000).toISOString(),copiedSessions[1].id]);
  for(const s of copiedSessions) await ops(`/sessions/${s.id}/attendance`,teacher,{records:[{studentId:learners[2].user.id,status:'present'}],minutes:60,complete:true},200,'PUT');
  assert((await ops('/my-certificates',learners[2])).length===0,'Certificate issued before final session ended.');
  await call('/api/internal/jobs/crm-outbox',null,undefined,401);
  await db.query('UPDATE attendance_sessions SET date=$1 WHERE id=$2',[new Date(Date.now()-120*60_000).toISOString(),copiedSessions[1].id]);
  const job=await call('/api/internal/jobs/crm-outbox',null,undefined,200,'GET',{Authorization:'Bearer local-cron-test-secret'});
  assert(job.certificates.checked>=1,'Background certificate reconciliation did not run.');
  assert((await ops('/my-certificates',learners[2])).length===1,'Delayed final session did not receive a certificate.');
  await call('/api/internal/jobs/crm-outbox',null,undefined,200,'GET',{Authorization:'Bearer local-cron-test-secret'});
  assert((await ops('/my-certificates',learners[2])).length===1,'Background reconciliation duplicated certificate.');
  console.log('5. CRM confirmation cannot place direct-sale learner');
  const crmLearner=await crm('/students',{name:'CRM Learner',email:`ops.crm.${run}@example.com`});
  const crmSession=await login(crmLearner.email,'LocalTestOnly_2026!');await call('/api/users/change-password',crmSession,{currentPassword:'LocalTestOnly_2026!',newPassword:'Student@67890'});
  const crmEnrollment=await crm('/enrollments',{email:crmLearner.email,courseId:course.id,sectionId:a.id,crmDealId:`deal-${run}`});
  const payment=await crm('/payments/confirm',{enrollmentId:crmEnrollment.enrollmentId,amount:1000000,sectionId:a.id});
  assert(payment.status==='pending' && payment.placedSectionId===null,'CRM incorrectly activated/placed learner.');
  assert(!(await db.query("SELECT 1 FROM course_registrations WHERE student_id=$1 AND status='registered'",[crmLearner.lmsUserId])).rowCount,'CRM created class seat.');
  console.log('6. Consultation, delegated sales, voucher reservations and manual payment');
  const requestKey=`lead-key-${run}`;const lead=await ops('/consultations',learners[0],{message:'Need next-course consultation',courseId:next.id,requestKey});
  const lead2=await ops('/consultations',learners[0],{message:'Need next-course consultation',courseId:next.id,requestKey});assert(lead.id===lead2.id,'Consultation retry duplicated lead.');
  await ops('/sales',manager,undefined,403);await ops(`/sales-permissions/${mgrRow.id}`,manager,{enabled:true},403,'PATCH');
  await ops(`/sales-permissions/${mgrRow.id}`,admin,{enabled:true},200,'PATCH');
  await ops('/recommendations',manager,{sourceCourseId:course.id,targetCourseIds:[next.id]},200,'PUT');
  const voucher=await ops('/vouchers',manager,{code:`TEST-${run}`,amount:300000,courseId:next.id,expiresAt:'2030-01-01T00:00:00Z',maxUses:1});
  const dispatch={studentIds:[learners[0].user.id],message:'Next-course voucher',voucherId:voucher.id,requestKey:`broadcast-${run}`};
  assert((await ops('/broadcast',manager,dispatch)).sent===1,'Broadcast did not send.');assert((await ops('/broadcast',manager,dispatch)).sent===0,'Broadcast retry sent duplicate.');
  assert((await ops('/my-offers',learners[0])).courses.some((c:any)=>c.id===next.id),'Completed-course upsell offer missing.');
  const orderInput={courseId:next.id,voucherCode:voucher.code,requestKey:`order-${run}`};const order=await ops('/upsell-orders',learners[0],orderInput);
  assert(Number(order.amount)===1700000 && Number(order.commission_rate)===.1 && order.source==='self','Order price or source incorrect.');
  assert((await ops('/upsell-orders',learners[0],orderInput)).id===order.id,'Retry created a new order.');
  await ops('/upsell-orders',learners[0],{...orderInput,courseId:course.id},409);
  await ops('/upsell-orders',manager,{studentId:learners[1].user.id,courseId:next.id,voucherCode:voucher.code,requestKey:`order2-${run}`},400);
  await ops(`/upsell-orders/${order.id}/confirm`,manager,{amount:1600000,reference:'Mismatch'},400);
  await Promise.all([1,2,3].map(()=>ops(`/upsell-orders/${order.id}/confirm`,manager,{amount:1700000,reference:`TRANSFER-${run}`})));
  await ops(`/upsell-orders/${order.id}/confirm`,manager,{amount:1700000,reference:'Changed transfer'},409);
  const paid=(await db.query('SELECT * FROM enrollments WHERE student_id=$1 AND course_id=$2',[learners[0].user.id,next.id])).rows[0];assert(paid.status==='pending','Upsell payment must wait for manager placement.');
  assert(Number((await db.query("SELECT COUNT(*)::int n FROM transactions WHERE student_id=$1 AND course_id=$2 AND status='approved'",[learners[0].user.id,next.id])).rows[0].n)===1,'Payment retry duplicated transaction.');
  const saleOrder=await ops('/upsell-orders',manager,{studentId:learners[1].user.id,courseId:next.id,requestKey:`sale-${run}`});assert(Number(saleOrder.commission_rate)===.05,'Consultation-source commission must be 5%.');
  const raceCourse=await call('/api/courses',manager,{title:`Race ${run}`,description:'Reservation concurrency test',teacherId:teacherRow.id,category:'Test',price:2000000,numberOfLessons:2},201);
  const raceVoucher=await ops('/vouchers',manager,{code:`RACE-${run}`,amount:300000,courseId:raceCourse.id,expiresAt:'2030-01-01T00:00:00Z',maxUses:1});
  const raced=await Promise.all(learners.slice(0,2).map((learner,i)=>ops('/upsell-orders',manager,{studentId:learner.user.id,courseId:raceCourse.id,voucherCode:raceVoucher.code,requestKey:`race-${run}-${i}`},[200,400])));
  assert(raced.filter(row=>row.id).length===1,'Concurrent voucher reservations exceeded max uses.');
  await call(`/api/course-sections/${a.id}`,manager,{...editClass,teacherId:otherRow.id,schedule:[{dayOfWeek:'Thứ Ba',startTime:'20:00',endTime:'22:00',room:'Online'}]},200,'PUT');
  const actualAfterEdit=(await db.query('SELECT teacher_id,date FROM attendance_sessions WHERE section_id=$1 ORDER BY date',[a.id])).rows;
  assert(actualAfterEdit.every((row,i)=>row.teacher_id===teacherRow.id && new Date(row.date).toISOString()===new Date(sessionsA[i].date).toISOString()),'Reassignment moved actual teaching history.');
  assert((await ops('/teaching?month=2026-09',teacher)).courses===2,'Reassignment erased historical class credit.');
  const ownerStore=await call('/api/store',otherTeacher);
  assert(!ownerStore.attendanceSessions.some((s:any)=>s.sectionId===copy.id),'Course owner leaked a class assigned to another teacher.');
  await ops(`/upsell-orders/${saleOrder.id}/cancel`,learners[0],{},400);
  await ops(`/sales-permissions/${mgrRow.id}`,admin,{enabled:false},200,'PATCH');await ops('/sales',manager,undefined,403);
  const outbox=(await db.query("SELECT event_type FROM crm_outbox WHERE event_type IN ('consultation.requested','upsell.requested','upsell.payment_confirmed')")).rows;assert(outbox.length>=4,'Lifecycle events missing from transactional outbox.');
  await call('/api/not-a-real-api',null,undefined,404);
  console.log(`Operations E2E complete: ${checks} checks passed.`);
}
main().catch(error=>{console.error(error);process.exitCode=1;}).finally(()=>db.end());
