import React,{useEffect,useRef,useState} from 'react';
import {operationsApi} from '../../api';
import {LMSDataStore} from '../../types';
import {buttonClass,inputClass,Field,Panel} from './OperationUI';

export default function SalesWorkspace({store,onChanged}:{store:LMSDataStore;onChanged:()=>void}) {
  const [data,setData]=useState<any>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  const [tab,setTab]=useState('leads'),[studentId,setStudentId]=useState(''),[courseId,setCourseId]=useState(''),[code,setCode]=useState(''),[amount,setAmount]=useState(300000),[expires,setExpires]=useState(''),[maxUses,setMaxUses]=useState(1);
  const [studentIds,setStudentIds]=useState<string[]>([]),[broadcast,setBroadcast]=useState(''),[voucherId,setVoucherId]=useState('');
  const [sourceCourseId,setSourceCourseId]=useState(''),[targetIds,setTargetIds]=useState<string[]>([]),[orderStudent,setOrderStudent]=useState(''),[orderCourse,setOrderCourse]=useState(''),[orderVoucher,setOrderVoucher]=useState('');
  const [confirm,setConfirm]=useState<any|null>(null),[reference,setReference]=useState('');
  const broadcastKey=useRef(crypto.randomUUID()),orderKey=useRef(crypto.randomUUID());
  const load=()=>operationsApi('/sales').then(setData);
  useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
  const run=async(fn:()=>Promise<any>,success='Đã lưu.')=>{setBusy(true);setMessage('');try{await fn();await load();onChanged();setMessage(success);}catch(e:any){setMessage(e.message);}finally{setBusy(false);}};
  const students=store.users.filter(u=>u.role==='student' && u.isActive),courses=store.courses.filter(c=>c.status==='published');
  return <div className="space-y-5">
    {message && <p role="status" className="rounded-lg bg-indigo-50 p-3 text-sm text-indigo-800">{message}</p>}
    {!data?<p className="text-sm text-slate-500">Chức năng dành cho admin hoặc Quản lý lớp được cấp quyền tư vấn.</p>:<>
      <nav aria-label="Tư vấn và ưu đãi" className="flex flex-wrap gap-2">{[['leads','Yêu cầu tư vấn'],['vouchers','Voucher & Thông báo'],['recommendations','Gợi ý học tiếp'],['orders','Đơn upsell']].map(([key,label])=><button key={key} className={`px-3 py-2 rounded-lg text-sm ${tab===key?'bg-indigo-50 text-indigo-700':'text-slate-600'}`} onClick={()=>setTab(key)}>{label}</button>)}</nav>
      {tab==='leads' && <Panel title="Yêu cầu cần tư vấn">{!data.consultations.length && <p className="text-sm text-slate-500">Chưa có yêu cầu.</p>}{data.consultations.map((lead:any)=><article key={lead.id} className="space-y-2 border-b border-slate-100 py-3"><p className="font-medium text-sm">{lead.name} · {lead.phone || lead.email}</p><p className="text-xs text-slate-500">{lead.course_title || 'Tư vấn chung'} · {new Date(lead.created_at).toLocaleString('vi-VN')}</p><p className="text-sm whitespace-pre-wrap">{lead.message}</p><select aria-label={`Trạng thái tư vấn ${lead.name}`} disabled={busy} className={inputClass} value={lead.status} onChange={e=>run(()=>operationsApi(`/consultations/${lead.id}`,{status:e.target.value},'PATCH'))}><option value="new">Chưa xử lý</option><option value="contacted">Đã liên hệ</option><option value="closed">Đã hoàn tất</option></select></article>)}</Panel>}
      {tab==='vouchers' && <>
        <Panel title="Tạo voucher"><form className="grid sm:grid-cols-2 gap-3" onSubmit={e=>{e.preventDefault();run(()=>operationsApi('/vouchers',{code,amount,courseId:courseId || undefined,studentId:studentId || undefined,expiresAt:new Date(expires).toISOString(),maxUses}),'Đã tạo voucher.');}}>
          <Field label="Mã voucher"><input required pattern="[A-Za-z0-9_-]{3,40}" className={inputClass} value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/></Field><Field label="Số tiền giảm (đ)"><input required type="number" min={1} className={inputClass} value={amount} onChange={e=>setAmount(Number(e.target.value))}/></Field>
          <Field label="Khóa áp dụng"><select className={inputClass} value={courseId} onChange={e=>setCourseId(e.target.value)}><option value="">Mọi khóa</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></Field>
          <Field label="Học viên áp dụng"><select className={inputClass} value={studentId} onChange={e=>setStudentId(e.target.value)}><option value="">Mọi học viên</option>{students.map(u=><option key={u.id} value={u.id}>{u.name} · {u.email}</option>)}</select></Field>
          <Field label="Hết hạn"><input required type="datetime-local" className={inputClass} value={expires} onChange={e=>setExpires(e.target.value)}/></Field><Field label="Tổng số lượt sử dụng"><input type="number" min={1} max={10000} required className={inputClass} value={maxUses} onChange={e=>setMaxUses(Number(e.target.value))}/></Field><button disabled={busy} className={buttonClass}>Tạo voucher</button>
        </form>
        <div className="space-y-1 text-sm">{data.vouchers.map((v:any)=><p key={v.id}>{v.code} · {Number(v.amount).toLocaleString('vi-VN')}đ · {new Date(v.expires_at).toLocaleString('vi-VN')}</p>)}</div></Panel>
        <Panel title="Gửi thông báo & Voucher"><form className="space-y-3" onSubmit={e=>{e.preventDefault();run(async()=>{await operationsApi('/broadcast',{studentIds,message:broadcast,voucherId:voucherId || undefined,requestKey:broadcastKey.current});broadcastKey.current=crypto.randomUUID();},'Đã gửi thông báo.');}}>
          <Field label="Thông báo"><textarea required minLength={2} maxLength={2000} className={inputClass} rows={3} value={broadcast} onChange={e=>setBroadcast(e.target.value)}/></Field><Field label="Đính kèm voucher"><select className={inputClass} value={voucherId} onChange={e=>setVoucherId(e.target.value)}><option value="">Không đính kèm</option>{data.vouchers.map((v:any)=><option key={v.id} value={v.id}>{v.code}</option>)}</select></Field>
          <fieldset className="max-h-64 overflow-y-auto grid sm:grid-cols-2 gap-2"><legend className="text-sm font-medium mb-2">Chọn người nhận ({studentIds.length})</legend>{students.map(u=><label key={u.id} className="flex gap-2 text-sm"><input type="checkbox" checked={studentIds.includes(u.id)} onChange={e=>setStudentIds(e.target.checked?[...studentIds,u.id]:studentIds.filter(id=>id!==u.id))}/>{u.name}</label>)}</fieldset><button disabled={busy || !studentIds.length} className={buttonClass}>Gửi thông báo</button>
        </form></Panel>
      </>}
      {tab==='recommendations' && <Panel title="Gợi ý khóa tiếp theo sau khi hoàn thành"><form className="space-y-3" onSubmit={e=>{e.preventDefault();run(()=>operationsApi('/recommendations',{sourceCourseId,targetCourseIds:targetIds},'PUT'));}}>
        <Field label="Khóa đã hoàn thành"><select required className={inputClass} value={sourceCourseId} onChange={e=>{setSourceCourseId(e.target.value);setTargetIds(data.recommendations.filter((r:any)=>r.source_course_id===e.target.value).map((r:any)=>r.target_course_id));}}><option value="">Chọn khóa</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></Field>
        <fieldset className="grid sm:grid-cols-2 gap-2"><legend className="font-medium text-sm mb-2">Khóa học tiếp theo</legend>{courses.filter(c=>c.id!==sourceCourseId).map(c=><label key={c.id} className="flex gap-2 text-sm"><input type="checkbox" checked={targetIds.includes(c.id)} onChange={e=>setTargetIds(e.target.checked?[...targetIds,c.id]:targetIds.filter(id=>id!==c.id))}/>{c.title}</label>)}</fieldset><button disabled={busy || !sourceCourseId} className={buttonClass}>Lưu gợi ý</button>
      </form></Panel>}
      {tab==='orders' && <Panel title="Đơn upsell & Xác nhận thủ công">
        <form className="grid sm:grid-cols-2 gap-3 border-b border-slate-200 pb-4" onSubmit={e=>{e.preventDefault();run(async()=>{await operationsApi('/upsell-orders',{studentId:orderStudent,courseId:orderCourse,voucherCode:orderVoucher || undefined,requestKey:orderKey.current});orderKey.current=crypto.randomUUID();},'Đã tạo đơn nguồn sale tư vấn.');}}>
          <Field label="Học viên"><select required className={inputClass} value={orderStudent} onChange={e=>setOrderStudent(e.target.value)}><option value="">Chọn học viên</option>{students.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Field><Field label="Khóa học"><select required className={inputClass} value={orderCourse} onChange={e=>setOrderCourse(e.target.value)}><option value="">Chọn khóa</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></Field><Field label="Voucher"><input className={inputClass} value={orderVoucher} onChange={e=>setOrderVoucher(e.target.value)}/></Field><button disabled={busy} className={buttonClass}>Tạo đơn qua sale</button>
        </form>
        {data.orders.map((o:any)=><article key={o.id} className="border-b border-slate-100 py-3 space-y-1"><p className="font-medium text-sm">{o.name} · {o.course_title}</p><p className="text-sm text-slate-600">{Number(o.amount).toLocaleString('vi-VN')}đ · {o.source==='self'?'Tự mua':'Sale tư vấn'} · Hoa hồng {o.commission_rate===null?'chưa áp dụng':`${Number(o.commission_rate)*100}%`} · {({pending:'Chờ xác nhận',paid:'Đã thanh toán',cancelled:'Đã hủy'} as any)[o.status]}</p><p className="text-xs text-slate-400">{o.id}</p>{o.status==='pending' && <div className="flex gap-3"><button disabled={busy} className="text-sm text-indigo-700" onClick={()=>{setConfirm(o);setReference('');}}>Xác nhận đã nhận tiền</button><button disabled={busy} className="text-sm text-rose-700" onClick={()=>run(()=>operationsApi(`/upsell-orders/${o.id}/cancel`,{}))}>Hủy đơn</button></div>}</article>)}
        {confirm && <form className="space-y-3 rounded-lg bg-amber-50 p-3" onSubmit={e=>{e.preventDefault();run(async()=>{await operationsApi(`/upsell-orders/${confirm.id}/confirm`,{amount:Number(confirm.amount),reference});setConfirm(null);},'Đã ghi nhận thanh toán. Học viên chờ Quản lý lớp xếp lớp.');}}><p className="text-sm">Xác nhận đã nhận đủ {Number(confirm.amount).toLocaleString('vi-VN')}đ cho {confirm.name}. Chỉ xác nhận sau khi đã đối chiếu tài khoản công ty.</p><Field label="Mã giao dịch / bằng chứng đối soát"><input required minLength={3} className={inputClass} value={reference} onChange={e=>setReference(e.target.value)}/></Field><div className="flex gap-3"><button disabled={busy} className={buttonClass}>Xác nhận thanh toán</button><button type="button" onClick={()=>setConfirm(null)}>Hủy</button></div></form>}
      </Panel>}
    </>}
  </div>;
}
